### ISSUE TITLE
Impact results layer not visible after running volcanic_ashonstructure

### ISSUE THREAD

**Issue by NyakudyaA** [inasafe/inasafe#2985]
### Problem

After running Ash on building centroids the resultant layer generated has correct symbology but it is not visible.

Layers before analysis.

![volc](https://cloud.githubusercontent.com/assets/2510900/16333114/d05bd268-39f9-11e6-95dc-0adb3cb5c376.png)

Layers after analysis

![volc_no_symbols](https://cloud.githubusercontent.com/assets/2510900/16333237/855d0376-39fa-11e6-9aef-29746cd278ba.png)

Impact results properties

![volc3](https://cloud.githubusercontent.com/assets/2510900/16333275/b90c9d6c-39fa-11e6-9756-1d7397591c87.png)
### Expected Behaviour

Render the layer with its symbols.
After I changed the symbology from categorized to rule based all works.

![volc4](https://cloud.githubusercontent.com/assets/2510900/16333329/04cfd840-39fb-11e6-986c-e1499f67ab4a.png)
### Environment
- InaSAFE :  3.5
- QGIS :  2.14.3
- OS :  Ubuntu 16.04
- Data used : From  `.qgis2/python/plugins/inasafe/safe/test/data`
  - Exposure :  `exposure/building-points.shp`
  - Hazard : `hazard/ash_raster_wgs84.tif`
  - Aggregation : `Entire Area`
### Proposed Solution

Render the layer generated from analysis

**Comment by Gustry** [comment]
I can replicate too.

I'm running the analysis in QGIS 2.8.9, the impact layer is loaded in the legend and I can see it in the canvas.
![selection_001](https://cloud.githubusercontent.com/assets/1609292/16407160/7e5f2eda-3d12-11e6-91f6-204ae3d959b1.png)

But if I'm running the same analysis in QGIS 2.14.3 or QGIS Master, the impact layer is not visible : 
![selection_002](https://cloud.githubusercontent.com/assets/1609292/16407236/f88f0fea-3d12-11e6-8163-294b7a90d2c5.png)
We can notice that the layer is not empty.

In order to see the layer, I can remove the layer from QGIS and add it again manually. The default style will be loaded and the layer will be visible.

**Comment by Gustry** [comment]
The IF impacted seems : "ClassifiedRasterHazardBuildingFunction". I didn't notice this problem with another IF. Only one.

And it seems related to QGIS, I tried with an old version of InaSAFE : 

  | InaSAFE 3.3.0 | Develop
-------------  | ------------ | -------------
QGIS 2.8 | :white_check_mark:  | :white_check_mark:
QGIS 2.14  | :no_entry_sign: | :no_entry_sign:

**Comment by ivanbusthomi** [comment]
I think it may be related to issues #2858

**Comment by ismailsunni** [comment]
I tried by using QGIS 2.14.2 on OSX, using InaSAFE develop. It works for me:
<img width="1394" alt="screen shot 2016-08-10 at 11 44 10" src="https://cloud.githubusercontent.com/assets/1421861/17542093/e6e88a88-5eef-11e6-896d-43eacf74228c.png">

**Comment by Gustry** [comment]
This ticket needs to be updated with InaSAFE v4.

**Comment by NyakudyaA** [comment]
I will look at it @Gustry

**Comment by NyakudyaA** [comment]
The problem still occurs:
QGIS Version: 2.14.3
Inasafe Version: develop
![error](https://cloud.githubusercontent.com/assets/2510900/22426500/1c56a2c2-e708-11e6-92cd-26a94c6c59d4.gif)

QGIS Version 2.18.2
Inasafe version: develop
Problem:
![errors](https://cloud.githubusercontent.com/assets/2510900/22426569/64d2f258-e708-11e6-87b1-0b12a0e25735.png)

```
These additional details were reported when the problem occurred.

'NoneType' object has no attribute 'copy'
Diagnostics

In file "/home/admire/.qgis2/python/plugins/inasafe/safe/impact_function/impact_function.py", line 977, in run self._run()
In file "/home/admire/.qgis2/python/plugins/inasafe/safe/utilities/profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "/home/admire/.qgis2/python/plugins/inasafe/safe/impact_function/impact_function.py", line 1126, in _run self.gis_overlay_analysis()
In file "/home/admire/.qgis2/python/plugins/inasafe/safe/utilities/profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "/home/admire/.qgis2/python/plugins/inasafe/safe/impact_function/impact_function.py", line 1207, in gis_overlay_analysis self.hazard_preparation()
In file "/home/admire/.qgis2/python/plugins/inasafe/safe/utilities/profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "/home/admire/.qgis2/python/plugins/inasafe/safe/impact_function/impact_function.py", line 1359, in hazard_preparation self.hazard = reclassify_raster(self.hazard)
In file "/home/admire/.qgis2/python/plugins/inasafe/safe/utilities/profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "/home/admire/.qgis2/python/plugins/inasafe/safe/gis/raster/reclassify.py", line 92, in reclassify destination = source.copy()

```

**Comment by Gustry** [comment]
So with both inasafe develop : 
* Working with QGIS 2.14
* Not working with QGIS 2.18, but a different error the original ticket.

Correct ?

**Comment by NyakudyaA** [comment]
yes @Gustry  It is giving a different error in 2.18.2 but running in QGIS 2.14.3 with the same error as the ticket stipulates

**Comment by Gustry** [comment]
![screen shot 2017-01-31 at 09 55 15](https://cloud.githubusercontent.com/assets/1609292/22458150/6ee7fbc4-e79b-11e6-937d-0ce6067e303e.png)

Everything is working in 2.14.10. I would need some inputs @NyakudyaA as I can't replicate.

**Comment by NyakudyaA** [comment]
@Gustry  I can replicate in 2.14.3 will try to run in 2.14.10 and 2.18

**Comment by NyakudyaA** [comment]
I have tested this and all works. Will proceed to open a related ticket.
