### ISSUE TITLE
Failure to open Inasafe plugin on upgrade to QGIS 2.16

### ISSUE THREAD

**Issue by NyakudyaA** [inasafe/inasafe#3026]
### Problem
After upgrading QGIS version from 2.14.3 to QGIS 2.16 Inasafe cannot start at all.

`Couldn't load plugin inasafe due to an error when calling its initGui() method 
ImportError: cannot import name MissingImpactReport 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 342, in startPlugin
    plugins[packageName].initGui()
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/plugin.py", line 448, in initGui
    self.toolbar = self.iface.addToolBar('InaSAFE')
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/plugin.py", line 424, in _create_dock
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 88, in 
    from safe.common.exceptions import (
ImportError: cannot import name MissingImpactReport
Python version: 2.7.11+ (default, Apr 17 2016, 14:00:29) [GCC 5.3.1 20160413] 
QGIS version: 2.16.0-Nødebo Nødebo, 2f9ed29` 

### Expected Behaviour
Start inasafe seamlessly irregardless of version.

### Environment
* InaSAFE :  3.4 and 3.5
* QGIS :  2.16
* OS :  Ubuntu 16.04
* Data used : 
  * Exposure : 
  * Hazard : 
  * Aggregation :

### Proposed Solution
Start Inasafe

**Comment by timlinux** [comment]
Can you update your checkout and validate that this is still the case? @Gustry will you take a look?

**Comment by timlinux** [comment]
Note also that we do not yet support 2.16 for InaSAFE.

**Comment by NyakudyaA** [comment]
ok @timlinux  I will continue using 2.14.3. Removed my checkout and installed inasafe through plugins manager and it is crushing QGIS.  We can close the ticket ?

**Comment by Gustry** [comment]
This error shouldn't occur, so we should fix this kind of exceptions.

**Comment by timlinux** [comment]
Yes we should fix it, I just don't consider it a blocker for the release. @NyakudyaA when I get back to the office I will look at it on your machine ok?

**Comment by timlinux** [comment]
I'm closing this. I tested on both 2.14 and 2.16 under windows and it is running fine.
