### ISSUE TITLE
Uncaught ImportError: cannot import name show_message_log


### ISSUE THREAD

**Issue by gubuntu** [inasafe/inasafe#3063]
Couldn't load plugin inasafe due to an error when calling its classFactory() method
Steps to reproduce
1. First 
   loads fine in 2.14 and 2.16 but get this error with 2.8 (my guess is because it's using the new processing api that doesn't work in 2.8 in which cas this isn't an inasafe bug)
2. Second 
3. Third 

```
Traceback (most recent call last):
  File "/usr/local/qgis-2.8/share/qgis/python/qgis/utils.py", line 219, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/gavin/.qgis2/python/plugins/inasafe/__init__.py", line 86, in classFactory
    from safe.plugin import Plugin
  File "/usr/local/qgis-2.8/share/qgis/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/gavin/.qgis2/python/plugins/inasafe/safe/plugin.py", line 47, in <module>
    from safe.impact_functions import register_impact_functions
  File "/usr/local/qgis-2.8/share/qgis/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/gavin/.qgis2/python/plugins/inasafe/safe/impact_functions/__init__.py", line 14, in <module>
    from safe.impact_functions.earthquake.earthquake_building\
  File "/usr/local/qgis-2.8/share/qgis/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/gavin/.qgis2/python/plugins/inasafe/safe/impact_functions/earthquake/earthquake_building/impact_function.py", line 19, in <module>
    from safe.impact_functions.bases.continuous_rh_classified_ve import \
  File "/usr/local/qgis-2.8/share/qgis/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/gavin/.qgis2/python/plugins/inasafe/safe/impact_functions/bases/continuous_rh_classified_ve.py", line 8, in <module>
    from safe.impact_functions.base import ImpactFunction
  File "/usr/local/qgis-2.8/share/qgis/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/gavin/.qgis2/python/plugins/inasafe/safe/impact_functions/base.py", line 35, in <module>
    from safe.impact_statistics.aggregator import Aggregator
  File "/usr/local/qgis-2.8/share/qgis/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/gavin/.qgis2/python/plugins/inasafe/safe/impact_statistics/aggregator.py", line 89, in <module>
    from processing.core.Processing import Processing
  File "/usr/local/qgis-2.8/share/qgis/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/gavin/.qgis2/python/plugins/processing/__init__.py", line 29, in <module>
    from processing.tools.general import *
  File "/usr/local/qgis-2.8/share/qgis/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/gavin/.qgis2/python/plugins/processing/tools/general.py", line 28, in <module>
    from processing.core.Processing import Processing
  File "/usr/local/qgis-2.8/share/qgis/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/gavin/.qgis2/python/plugins/processing/core/Processing.py", line 46, in <module>
    from processing.modeler.ModelerAlgorithmProvider import ModelerAlgorithmProvider
  File "/usr/local/qgis-2.8/share/qgis/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/gavin/.qgis2/python/plugins/processing/modeler/ModelerAlgorithmProvider.py", line 42, in <module>
    from processing.gui.GetScriptsAndModels import GetModelsAction
  File "/usr/local/qgis-2.8/share/qgis/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/gavin/.qgis2/python/plugins/processing/gui/GetScriptsAndModels.py", line 38, in <module>
    from qgis.utils import iface, show_message_log
ImportError: cannot import name show_message_log

```

inasafe 3.4.2, QGIS 2.8.9-Wien on Linux 4.4.0-31-generic

**Comment by Gustry** [comment]
@gubuntu We don't support QGIS 2.8 now.
I'm going to close this issue.
